name: Run Casting Tracker Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  run-casting-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install feedparser python-dotenv openai requests

      - name: Install dependencies
        run: |
          pip install feedparser python-dotenv openai
   
      - name: Install dependencies
        run: |
          pip install feedparser python-dotenv openai httpx

      - name: Run Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python casting_tracker.py

      - name: Commit & Push Report
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_NEW }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/lebron1212/casting-tracker.git
          git add reports/
          git commit -m "Auto: Add casting report" || echo "Nothing to commit"
          git push origin HEAD:main || echo "Nothing to push"
